appname = Rincones_llaneros
httpport = 8082
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = postgres://postgres:postgres@127.0.0.1/Rincones_llaneros?sslmode=disable
